<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-MIHB6U5" failures="2" tests="2" name="Test(failed)" time="0.09" errors="0" timestamp="2023-02-13T19:56:22 IST">
  <testcase classname="TestNG.Demo3" name="TC6" time="0.014">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG.Demo3.TC6(Demo3.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC6 -->
  <testcase classname="TestNG.Demo2" name="TC3" time="0.003">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG.Demo2.TC3(Demo2.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC3 -->
  <testcase classname="TestNG.Demo3" name="TC5" time="0.0">
    <ignored/>
  </testcase> <!-- TC5 -->
  <testcase classname="TestNG.Demo2" name="TC4" time="0.0">
    <ignored/>
  </testcase> <!-- TC4 -->
</testsuite> <!-- Test(failed) -->
